# Generated by Django 3.1.1 on 2020-09-08 23:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Token created')),
                ('entered', models.IntegerField(default=0, editable=False, verbose_name='URL use count')),
                ('last_visited', models.DateTimeField(auto_now=True, verbose_name='Last visit')),
                ('active', models.BooleanField(default=True, verbose_name='Access allowed')),
            ],
        ),
    ]
