# Generated by Django 3.1.1 on 2020-09-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linksapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtoken',
            options={'ordering': ['-created']},
        ),
    ]
